In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [16]:
df =df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [18]:
# create a column age_group
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels=labels)

In [19]:
df[['age','age_group']].head()

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged

In [26]:
# create column purchase_frequency_days
frequency_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Annually':365,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Monthly':30,
    'Every 3 Months':90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [27]:
df[['frequency_of_purchases','purchase_frequency_days']].head()

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365

In [28]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [30]:
#both columns carry same info
df = df.drop('promo_code_used',axis=1)

In [31]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [32]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Obtaining dependency information for psycopg2-binary from https://files.pythonhosted.org/packages/27/64/6e3a96699770af2d0d49a2002f722c69b656fc27623ff89281cf2b109644/psycopg2_binary-2.9.13-cp312-cp312-win_amd64.whl.metadata
  Downloading psycopg2_binary-2.9.13-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Obtaining dependency information for sqlalchemy from https://files.pythonhosted.org/packages/ed/06/543dab8ef62d4e9fb96fb31a30c2b8b14a8763bccf48d428294d6b3041c0/sqlalchemy-2.0.52-cp312-cp312-win_amd64.whl.metadata
  Downloading sqlalchemy-2.0.52-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Obtaining dependency information for greenlet>=1 from https://files.pythonhosted.org/packages/de/30/1f42b88dc587b5899ee50616ad56ee40cafaf225df4fb829f10183c62a5c/greenlet-3.5.5-cp312-cp312-win_amd64.whl.metadata
  Downloading greenlet-3.5.5-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\adnan khan\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.14.1)
Downloading psycopg2_binary-2.9.13-cp312-cp312-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB 131.3 kB/s eta 0:00:21
   ---------------------------------------- 0.0/2.8 MB 131.3 kB/s eta 0:00:21
    --------------------------------------- 0.0/2.8 MB 196.9 kB/s eta 0:00:14
    --------------------------------------- 0.1/2.8 MB 252.2 kB/s eta 0:00:11
   - -------------------------------------- 0.1/2.8 MB 306.3 kB/s eta 0:00:09
   - -------------------------------------- 0.1/2.8 MB 379.3 kB/s eta 0:00:07
   -- ------------------------------------- 0.1/2.8 MB 405.9 kB/s eta 0:00:07
   -- ------------------------------------- 0.2/2.8 MB 420.1 kB/s eta 0:00:07
   -- ------------------------------------- 0.2/2.8 MB 429.5 kB/s eta 0:00:06
   --- ------------------------------------ 0.2/2.8 MB 419.1 kB/s eta 0:00:07
   --- ------------------------------------ 0.3/2.8 MB 405.9 kB/s eta 0:00:07
   ---- ----------------------------------- 0.3/2.8 MB 384.5 kB/s eta 0:00:07
   ---- ----------------------------------- 0.3/2.8 MB 384.5 kB/s eta 0:00:07
   ---- ----------------------------------- 0.3/2.8 MB 372.6 kB/s eta 0:00:07
   ---- ----------------------------------- 0.3/2.8 MB 376.1 kB/s eta 0:00:07
   ---- ----------------------------------- 0.3/2.8 MB 368.2 kB/s eta 0:00:07
   ---- ----------------------------------- 0.3/2.8 MB 368.2 kB/s eta 0:00:07
   ----- ---------------------------------- 0.4/2.8 MB 353.8 kB/s eta 0:00:07
   ----- ---------------------------------- 0.4/2.8 MB 356.8 kB/s eta 0:00:07
   ----- ---------------------------------- 0.4/2.8 MB 356.8 kB/s eta 0:00:07
   ----- ---------------------------------- 0.4/2.8 MB 340.8 kB/s eta 0:00:07
   ----- ---------------------------------- 0.4/2.8 MB 340.8 kB/s eta 0:00:07
   ------ --------------------------------- 0.4/2.8 MB 323.8 kB/s eta 0:00:08
   ------ --------------------------------- 0.4/2.8 MB 323.9 kB/s eta 0:00:08
   ------ --------------------------------- 0.5/2.8 MB 316.8 kB/s eta 0:00:08
   ------ --------------------------------- 0.5/2.8 MB 317.1 kB/s eta 0:00:08
   ------ --------------------------------- 0.5/2.8 MB 317.1 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.8 MB 317.7 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.8 MB 311.5 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.8 MB 311.5 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.8 MB 309.2 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.8 MB 301.2 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.8 MB 301.2 kB/s eta 0:00:08
   ------- -------------------------------- 0.6/2.8 MB 302.0 kB/s eta 0:00:08
   -------- ------------------------------- 0.6/2.8 MB 303.0 kB/s eta 0:00:08
   -------- ------------------------------- 0.6/2.8 MB 303.0 kB/s eta 0:00:08
   -------- ------------------------------- 0.6/2.8 MB 296.0 kB/s eta 0:00:08
   -------- ------------------------------- 0.6/2.8 MB 297.0 kB/s eta 0:00:08
   -------- ------------------------------- 0.6/2.8 MB 293.0 kB/s eta 0:00:08
   -------- ------------------------------- 0.6/2.8 MB 293.0 kB/s eta 0:00:08
   -------- ------------------------------- 0.6/2.8 MB 293.0 kB/s eta 0:00:08
   --------- ------------------------------ 0.6/2.8 MB 287.6 kB/s eta 0:00:08
   --------- ------------------------------ 0.6/2.8 MB 287.6 kB/s eta 0:00:08
   --------- ------------------------------ 0.7/2.8 MB 282.8 kB/s eta 0:00:08
   --------- ------------------------------ 0.7/2.8 MB 282.8 kB/s eta 0:00:08
   --------- ------------------------------ 0.7/2.8 MB 274.2 kB/s eta 0:00:08
   --------- ------------------------------ 0.7/2.8 MB 274.2 kB/s eta 0:00:08
   --------- ------------------------------ 0.7/2.8 MB 273.7 kB/s eta 0:00:08
   ---------- ----------------------------- 0.7/2.8 MB 271.1 kB/s eta 0:00:08
   ---------- ----------------------------- 0.7/2.8 MB 271.1 kB/s eta 0:00:08
   ---------- ----------------------------- 0.7/2.8 MB 270.8 kB/s eta 0:00:08
   ---------- ----------------------------- 0.7/2.8 MB 273.7 kB/s eta 0:00:08
   ---------- ----------------------------- 0.7/2.8 MB 269.7 kB/s eta 0:00:08
   ---------- ----------------------------- 0.7/2.8 MB 269.7 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 270.9 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 267.1 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 267.0 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 267.0 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 266.9 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 266.9 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 260.9 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 260.9 kB/s eta 0:00:08
   ------------ --------------------------- 0.9/2.8 MB 260.3 kB/s eta 0:00:08
   ------------ --------------------------- 0.9/2.8 MB 260.3 kB/s eta 0:00:08
   ------------ --------------------------- 0.9/2.8 MB 260.3 kB/s eta 0:00:08
   ------------- -------------------------- 0.9/2.8 MB 260.3 kB/s eta 0:00:08
   ------------- -------------------------- 0.9/2.8 MB 260.3 kB/s eta 0:00:08
   ------------- -------------------------- 0.9/2.8 MB 259.8 kB/s eta 0:00:08
   ------------- -------------------------- 0.9/2.8 MB 258.7 kB/s eta 0:00:08
   ------------- -------------------------- 0.9/2.8 MB 258.7 kB/s eta 0:00:08
   ------------- -------------------------- 0.9/2.8 MB 257.1 kB/s eta 0:00:08
   ------------- -------------------------- 0.9/2.8 MB 257.1 kB/s eta 0:00:08
   ------------- -------------------------- 1.0/2.8 MB 256.1 kB/s eta 0:00:08
   -------------- ------------------------- 1.0/2.8 MB 258.4 kB/s eta 0:00:07
   -------------- ------------------------- 1.0/2.8 MB 256.8 kB/s eta 0:00:07
   -------------- ------------------------- 1.0/2.8 MB 256.8 kB/s eta 0:00:07
   -------------- ------------------------- 1.0/2.8 MB 258.0 kB/s eta 0:00:07
   -------------- ------------------------- 1.0/2.8 MB 255.4 kB/s eta 0:00:07
   -------------- ------------------------- 1.0/2.8 MB 255.4 kB/s eta 0:00:07
   --------------- ------------------------ 1.0/2.8 MB 255.6 kB/s eta 0:00:07
   --------------- ------------------------ 1.1/2.8 MB 255.7 kB/s eta 0:00:07
   --------------- ------------------------ 1.1/2.8 MB 255.7 kB/s eta 0:00:07
   --------------- ------------------------ 1.1/2.8 MB 253.4 kB/s eta 0:00:07
   --------------- ------------------------ 1.1/2.8 MB 253.4 kB/s eta 0:00:07
   --------------- ------------------------ 1.1/2.8 MB 253.5 kB/s eta 0:00:07
   --------------- ------------------------ 1.1/2.8 MB 251.4 kB/s eta 0:00:07
   ---------------- ----------------------- 1.1/2.8 MB 253.3 kB/s eta 0:00:07
   ---------------- ----------------------- 1.1/2.8 MB 251.2 kB/s eta 0:00:07
   ---------------- ----------------------- 1.1/2.8 MB 251.2 kB/s eta 0:00:07
   ---------------- ----------------------- 1.2/2.8 MB 250.5 kB/s eta 0:00:07
   ---------------- ----------------------- 1.2/2.8 MB 249.4 kB/s eta 0:00:07
   ---------------- ----------------------- 1.2/2.8 MB 249.4 kB/s eta 0:00:07
   ----------------- ---------------------- 1.2/2.8 MB 250.4 kB/s eta 0:00:07
   ----------------- ---------------------- 1.2/2.8 MB 250.4 kB/s eta 0:00:07
   ----------------- ---------------------- 1.2/2.8 MB 249.8 kB/s eta 0:00:07
   ----------------- ---------------------- 1.2/2.8 MB 249.8 kB/s eta 0:00:07
   ----------------- ---------------------- 1.2/2.8 MB 247.1 kB/s eta 0:00:07
   ----------------- ---------------------- 1.2/2.8 MB 248.1 kB/s eta 0:00:07
   ----------------- ---------------------- 1.2/2.8 MB 248.1 kB/s eta 0:00:07
   ------------------ --------------------- 1.2/2.8 MB 246.3 kB/s eta 0:00:07
   ------------------ --------------------- 1.3/2.8 MB 247.3 kB/s eta 0:00:07
   ------------------ --------------------- 1.3/2.8 MB 249.0 kB/s eta 0:00:06
   ------------------ --------------------- 1.3/2.8 MB 248.7 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 249.7 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 249.4 kB/s eta 0:00:06
   ------------------- -------------------- 1.4/2.8 MB 250.3 kB/s eta 0:00:06
   ------------------- -------------------- 1.4/2.8 MB 251.9 kB/s eta 0:00:06
   ------------------- -------------------- 1.4/2.8 MB 251.9 kB/s eta 0:00:06
   ------------------- -------------------- 1.4/2.8 MB 250.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.4/2.8 MB 250.2 kB/s eta 0:00:06
   -------------------- ------------------- 1.4/2.8 MB 250.4 kB/s eta 0:00:06
   -------------------- ------------------- 1.4/2.8 MB 249.4 kB/s eta 0:00:06
   -------------------- ------------------- 1.4/2.8 MB 249.6 kB/s eta 0:00:06
   -------------------- ------------------- 1.4/2.8 MB 248.0 kB/s eta 0:00:06
   --------------------- ------------------ 1.5/2.8 MB 249.8 kB/s eta 0:00:06
   --------------------- ------------------ 1.5/2.8 MB 248.8 kB/s eta 0:00:06
   --------------------- ------------------ 1.5/2.8 MB 249.0 kB/s eta 0:00:06
   --------------------- ------------------ 1.5/2.8 MB 249.4 kB/s eta 0:00:06
   --------------------- ------------------ 1.5/2.8 MB 250.9 kB/s eta 0:00:05
   ---------------------- ----------------- 1.5/2.8 MB 252.3 kB/s eta 0:00:05
   ---------------------- ----------------- 1.5/2.8 MB 251.4 kB/s eta 0:00:05
   ---------------------- ----------------- 1.6/2.8 MB 252.2 kB/s eta 0:00:05
   ---------------------- ----------------- 1.6/2.8 MB 251.9 kB/s eta 0:00:05
   ----------------------- ---------------- 1.6/2.8 MB 253.3 kB/s eta 0:00:05
   ----------------------- ---------------- 1.6/2.8 MB 253.8 kB/s eta 0:00:05
   ----------------------- ---------------- 1.6/2.8 MB 255.1 kB/s eta 0:00:05
   ----------------------- ---------------- 1.7/2.8 MB 254.3 kB/s eta 0:00:05
   ------------------------ --------------- 1.7/2.8 MB 254.9 kB/s eta 0:00:05
   ------------------------ --------------- 1.7/2.8 MB 256.2 kB/s eta 0:00:05
   ------------------------ --------------- 1.7/2.8 MB 256.0 kB/s eta 0:00:05
   ------------------------ --------------- 1.7/2.8 MB 256.0 kB/s eta 0:00:05
   ------------------------- -------------- 1.7/2.8 MB 256.4 kB/s eta 0:00:05
   ------------------------- -------------- 1.7/2.8 MB 256.4 kB/s eta 0:00:05
   ------------------------- -------------- 1.8/2.8 MB 256.4 kB/s eta 0:00:04
   ------------------------- -------------- 1.8/2.8 MB 257.1 kB/s eta 0:00:04
   ------------------------- -------------- 1.8/2.8 MB 255.7 kB/s eta 0:00:04
   -------------------------- ------------- 1.8/2.8 MB 256.3 kB/s eta 0:00:04
   -------------------------- ------------- 1.8/2.8 MB 256.3 kB/s eta 0:00:04
   -------------------------- ------------- 1.8/2.8 MB 255.0 kB/s eta 0:00:04
   -------------------------- ------------- 1.8/2.8 MB 255.6 kB/s eta 0:00:04
   -------------------------- ------------- 1.8/2.8 MB 255.6 kB/s eta 0:00:04
   -------------------------- ------------- 1.9/2.8 MB 255.6 kB/s eta 0:00:04
   --------------------------- ------------ 1.9/2.8 MB 254.9 kB/s eta 0:00:04
   --------------------------- ------------ 1.9/2.8 MB 256.0 kB/s eta 0:00:04
   --------------------------- ------------ 1.9/2.8 MB 255.2 kB/s eta 0:00:04
   --------------------------- ------------ 1.9/2.8 MB 255.3 kB/s eta 0:00:04
   ---------------------------- ----------- 1.9/2.8 MB 255.4 kB/s eta 0:00:04
   ---------------------------- ----------- 2.0/2.8 MB 254.1 kB/s eta 0:00:04
   ---------------------------- ----------- 2.0/2.8 MB 254.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.0/2.8 MB 253.5 kB/s eta 0:00:04
   ---------------------------- ----------- 2.0/2.8 MB 253.5 kB/s eta 0:00:04
   ----------------------------- ---------- 2.0/2.8 MB 253.6 kB/s eta 0:00:04
   ----------------------------- ---------- 2.0/2.8 MB 253.6 kB/s eta 0:00:04
   ----------------------------- ---------- 2.0/2.8 MB 253.7 kB/s eta 0:00:03
   ----------------------------- ---------- 2.0/2.8 MB 252.5 kB/s eta 0:00:03
   ----------------------------- ---------- 2.0/2.8 MB 252.5 kB/s eta 0:00:03
   ----------------------------- ---------- 2.1/2.8 MB 253.0 kB/s eta 0:00:03
   ----------------------------- ---------- 2.1/2.8 MB 251.9 kB/s eta 0:00:03
   ----------------------------- ---------- 2.1/2.8 MB 251.9 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.8 MB 251.5 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.8 MB 251.5 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.8 MB 251.6 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.8 MB 252.2 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.8 MB 250.6 kB/s eta 0:00:03
   ------------------------------ --------- 2.1/2.8 MB 250.6 kB/s eta 0:00:03
   ------------------------------- -------- 2.2/2.8 MB 250.7 kB/s eta 0:00:03
   ------------------------------- -------- 2.2/2.8 MB 249.6 kB/s eta 0:00:03
   ------------------------------- -------- 2.2/2.8 MB 249.6 kB/s eta 0:00:03
   ------------------------------- -------- 2.2/2.8 MB 250.2 kB/s eta 0:00:03
   ------------------------------- -------- 2.2/2.8 MB 251.2 kB/s eta 0:00:03
   ------------------------------- -------- 2.2/2.8 MB 251.2 kB/s eta 0:00:03
   -------------------------------- ------- 2.2/2.8 MB 250.1 kB/s eta 0:00:03
   -------------------------------- ------- 2.2/2.8 MB 250.7 kB/s eta 0:00:03
   -------------------------------- ------- 2.3/2.8 MB 250.5 kB/s eta 0:00:03
   -------------------------------- ------- 2.3/2.8 MB 250.5 kB/s eta 0:00:03
   -------------------------------- ------- 2.3/2.8 MB 250.1 kB/s eta 0:00:02
   -------------------------------- ------- 2.3/2.8 MB 250.1 kB/s eta 0:00:02
   --------------------------------- ------ 2.3/2.8 MB 249.8 kB/s eta 0:00:02
   --------------------------------- ------ 2.3/2.8 MB 249.8 kB/s eta 0:00:02
   --------------------------------- ------ 2.3/2.8 MB 248.4 kB/s eta 0:00:02
   --------------------------------- ------ 2.3/2.8 MB 248.9 kB/s eta 0:00:02
   --------------------------------- ------ 2.3/2.8 MB 248.9 kB/s eta 0:00:02
   --------------------------------- ------ 2.3/2.8 MB 247.1 kB/s eta 0:00:02
   --------------------------------- ------ 2.3/2.8 MB 247.1 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 246.8 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 246.8 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 246.6 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 246.6 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 245.6 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 245.6 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 245.4 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 244.1 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 244.1 kB/s eta 0:00:02
   ----------------------------------- ---- 2.4/2.8 MB 243.8 kB/s eta 0:00:02
   ----------------------------------- ---- 2.4/2.8 MB 243.8 kB/s eta 0:00:02
   ----------------------------------- ---- 2.5/2.8 MB 243.6 kB/s eta 0:00:02
   ----------------------------------- ---- 2.5/2.8 MB 243.6 kB/s eta 0:00:02
   ----------------------------------- ---- 2.5/2.8 MB 242.7 kB/s eta 0:00:02
   ----------------------------------- ---- 2.5/2.8 MB 242.7 kB/s eta 0:00:02
   ----------------------------------- ---- 2.5/2.8 MB 242.5 kB/s eta 0:00:02
   ----------------------------------- ---- 2.5/2.8 MB 242.5 kB/s eta 0:00:02
   ------------------------------------ --- 2.5/2.8 MB 240.9 kB/s eta 0:00:02
   ------------------------------------ --- 2.5/2.8 MB 240.9 kB/s eta 0:00:02
   ------------------------------------ --- 2.5/2.8 MB 240.7 kB/s eta 0:00:02
   ------------------------------------ --- 2.5/2.8 MB 240.7 kB/s eta 0:00:02
   ------------------------------------ --- 2.5/2.8 MB 240.2 kB/s eta 0:00:01
   ------------------------------------ --- 2.5/2.8 MB 238.7 kB/s eta 0:00:01
   ------------------------------------ --- 2.5/2.8 MB 238.7 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 238.8 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 238.8 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 237.7 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 237.7 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 237.5 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 237.5 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 237.7 kB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 237.7 kB/s eta 0:00:01
   -------------------------------------- - 2.7/2.8 MB 237.5 kB/s eta 0:00:01
   -------------------------------------- - 2.7/2.8 MB 237.5 kB/s eta 0:00:01
   -------------------------------------- - 2.7/2.8 MB 237.5 kB/s eta 0:00:01
   -------------------------------------- - 2.7/2.8 MB 235.7 kB/s eta 0:00:01
   -------------------------------------- - 2.7/2.8 MB 235.7 kB/s eta 0:00:01
   -------------------------------------- - 2.7/2.8 MB 235.6 kB/s eta 0:00:01
   ---------------------------------------  2.7/2.8 MB 235.5 kB/s eta 0:00:01
   ---------------------------------------  2.7/2.8 MB 235.5 kB/s eta 0:00:01
   ---------------------------------------  2.7/2.8 MB 234.4 kB/s eta 0:00:01
   ---------------------------------------  2.7/2.8 MB 234.4 kB/s eta 0:00:01
   ---------------------------------------  2.7/2.8 MB 234.6 kB/s eta 0:00:01
   ---------------------------------------  2.7/2.8 MB 234.6 kB/s eta 0:00:01
   ---------------------------------------  2.7/2.8 MB 233.9 kB/s eta 0:00:01
   ---------------------------------------  2.8/2.8 MB 232.9 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 233.1 kB/s eta 0:00:00
Downloading sqlalchemy-2.0.52-cp312-cp312-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
    --------------------------------------- 0.0/2.2 MB 220.2 kB/s eta 0:00:10
    --------------------------------------- 0.0/2.2 MB 220.2 kB/s eta 0:00:10
    --------------------------------------- 0.0/2.2 MB 178.6 kB/s eta 0:00:12

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: C:\Users\Adnan Khan\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [35]:
from sqlalchemy import create_engine
# connect to postgreSQL
username = 'postgres'
password = 'Adnan123'
host = 'localhost'
port = '5432'
database = 'customer_behavior_analysis'

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{databse}")

# load Dataframe into postgreq
table_name = 'customer'
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Data successfully loaded into table {table_name} in database {database}.")

Data successfully loaded into table customer in database customer_behavior_analysis.